services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.1
    container_name: elasticsearch
    environment:
      - node.name=node1
      - cluster.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - path.repo=/usr/share/elasticsearch/backups
      - ES_JAVA_OPTS=-Xms512m -Xmx512m 
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - node1-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.1
    container_name: kibana
    environment:
      - elasticsearch.url=http://elasticsearch:9200
      - csp.strict=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 5601:5601
    networks:
      - elasticsearch
    depends_on: 
      - elasticsearch

volumes:
  node1-data:
    driver: local

networks:
  elasticsearch:
